// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ipc/Command.proto

package edu.rit.se.sars.communication.proto.ipc.command;

public final class CommandOuterClass {
  private CommandOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Command_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Command_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Command_TakeoffCommand_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Command_TakeoffCommand_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Command_LandCommand_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Command_LandCommand_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Command_MoveToCommand_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Command_MoveToCommand_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Command_MoveGimbalCommand_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Command_MoveGimbalCommand_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Command_ChangeZoomLevelCommand_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Command_ChangeZoomLevelCommand_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Command_GetPositionCommand_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Command_GetPositionCommand_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Command_GetOrientationCommand_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Command_GetOrientationCommand_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Command_GetConnectionStateCommand_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Command_GetConnectionStateCommand_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021ipc/Command.proto\032\023common/Domain.proto" +
      "\"\365\005\n\007Command\022\014\n\004uuid\030\001 \001(\014\022*\n\007takeoff\030\002 " +
      "\001(\0132\027.Command.TakeoffCommandH\000\022$\n\004land\030\003" +
      " \001(\0132\024.Command.LandCommandH\000\022(\n\006moveTo\030\004" +
      " \001(\0132\026.Command.MoveToCommandH\000\0220\n\nmoveGi" +
      "mbal\030\005 \001(\0132\032.Command.MoveGimbalCommandH\000" +
      "\022:\n\017changeZoomLevel\030\006 \001(\0132\037.Command.Chan" +
      "geZoomLevelCommandH\000\0222\n\013getPosition\030\007 \001(" +
      "\0132\033.Command.GetPositionCommandH\000\0228\n\016getO" +
      "rientation\030\010 \001(\0132\036.Command.GetOrientatio" +
      "nCommandH\000\022@\n\022getConnectionState\030\t \001(\0132\"" +
      ".Command.GetConnectionStateCommandH\000\032\020\n\016" +
      "TakeoffCommand\032\r\n\013LandCommand\032c\n\rMoveToC" +
      "ommand\022\"\n\ntoLocation\030\001 \001(\0132\016.GeoLocation" +
      "3D\022\033\n\016headingDegrees\030\002 \001(\001H\000\210\001\001B\021\n\017_head" +
      "ingDegrees\0328\n\021MoveGimbalCommand\022#\n\rtoOri" +
      "entation\030\001 \001(\0132\014.Orientation\032+\n\026ChangeZo" +
      "omLevelCommand\022\021\n\tzoomLevel\030\001 \001(\001\032\024\n\022Get" +
      "PositionCommand\032\027\n\025GetOrientationCommand" +
      "\032\033\n\031GetConnectionStateCommandB\t\n\007command" +
      "B3\n/edu.rit.se.sars.communication.proto." +
      "ipc.commandP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          edu.rit.se.sars.communication.proto.common.domain.Domain.getDescriptor(),
        });
    internal_static_Command_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Command_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Command_descriptor,
        new java.lang.String[] { "Uuid", "Takeoff", "Land", "MoveTo", "MoveGimbal", "ChangeZoomLevel", "GetPosition", "GetOrientation", "GetConnectionState", "Command", });
    internal_static_Command_TakeoffCommand_descriptor =
      internal_static_Command_descriptor.getNestedTypes().get(0);
    internal_static_Command_TakeoffCommand_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Command_TakeoffCommand_descriptor,
        new java.lang.String[] { });
    internal_static_Command_LandCommand_descriptor =
      internal_static_Command_descriptor.getNestedTypes().get(1);
    internal_static_Command_LandCommand_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Command_LandCommand_descriptor,
        new java.lang.String[] { });
    internal_static_Command_MoveToCommand_descriptor =
      internal_static_Command_descriptor.getNestedTypes().get(2);
    internal_static_Command_MoveToCommand_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Command_MoveToCommand_descriptor,
        new java.lang.String[] { "ToLocation", "HeadingDegrees", "HeadingDegrees", });
    internal_static_Command_MoveGimbalCommand_descriptor =
      internal_static_Command_descriptor.getNestedTypes().get(3);
    internal_static_Command_MoveGimbalCommand_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Command_MoveGimbalCommand_descriptor,
        new java.lang.String[] { "ToOrientation", });
    internal_static_Command_ChangeZoomLevelCommand_descriptor =
      internal_static_Command_descriptor.getNestedTypes().get(4);
    internal_static_Command_ChangeZoomLevelCommand_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Command_ChangeZoomLevelCommand_descriptor,
        new java.lang.String[] { "ZoomLevel", });
    internal_static_Command_GetPositionCommand_descriptor =
      internal_static_Command_descriptor.getNestedTypes().get(5);
    internal_static_Command_GetPositionCommand_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Command_GetPositionCommand_descriptor,
        new java.lang.String[] { });
    internal_static_Command_GetOrientationCommand_descriptor =
      internal_static_Command_descriptor.getNestedTypes().get(6);
    internal_static_Command_GetOrientationCommand_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Command_GetOrientationCommand_descriptor,
        new java.lang.String[] { });
    internal_static_Command_GetConnectionStateCommand_descriptor =
      internal_static_Command_descriptor.getNestedTypes().get(7);
    internal_static_Command_GetConnectionStateCommand_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Command_GetConnectionStateCommand_descriptor,
        new java.lang.String[] { });
    edu.rit.se.sars.communication.proto.common.domain.Domain.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
