// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ipc/Command.proto

package edu.rit.se.sars.communication.proto.ipc.command;

public interface CommandOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Command)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bytes uuid = 1;</code>
   * @return The uuid.
   */
  com.google.protobuf.ByteString getUuid();

  /**
   * <code>.Command.TakeoffCommand takeoff = 2;</code>
   * @return Whether the takeoff field is set.
   */
  boolean hasTakeoff();
  /**
   * <code>.Command.TakeoffCommand takeoff = 2;</code>
   * @return The takeoff.
   */
  edu.rit.se.sars.communication.proto.ipc.command.Command.TakeoffCommand getTakeoff();
  /**
   * <code>.Command.TakeoffCommand takeoff = 2;</code>
   */
  edu.rit.se.sars.communication.proto.ipc.command.Command.TakeoffCommandOrBuilder getTakeoffOrBuilder();

  /**
   * <code>.Command.LandCommand land = 3;</code>
   * @return Whether the land field is set.
   */
  boolean hasLand();
  /**
   * <code>.Command.LandCommand land = 3;</code>
   * @return The land.
   */
  edu.rit.se.sars.communication.proto.ipc.command.Command.LandCommand getLand();
  /**
   * <code>.Command.LandCommand land = 3;</code>
   */
  edu.rit.se.sars.communication.proto.ipc.command.Command.LandCommandOrBuilder getLandOrBuilder();

  /**
   * <code>.Command.MoveToCommand moveTo = 4;</code>
   * @return Whether the moveTo field is set.
   */
  boolean hasMoveTo();
  /**
   * <code>.Command.MoveToCommand moveTo = 4;</code>
   * @return The moveTo.
   */
  edu.rit.se.sars.communication.proto.ipc.command.Command.MoveToCommand getMoveTo();
  /**
   * <code>.Command.MoveToCommand moveTo = 4;</code>
   */
  edu.rit.se.sars.communication.proto.ipc.command.Command.MoveToCommandOrBuilder getMoveToOrBuilder();

  /**
   * <code>.Command.MoveGimbalCommand moveGimbal = 5;</code>
   * @return Whether the moveGimbal field is set.
   */
  boolean hasMoveGimbal();
  /**
   * <code>.Command.MoveGimbalCommand moveGimbal = 5;</code>
   * @return The moveGimbal.
   */
  edu.rit.se.sars.communication.proto.ipc.command.Command.MoveGimbalCommand getMoveGimbal();
  /**
   * <code>.Command.MoveGimbalCommand moveGimbal = 5;</code>
   */
  edu.rit.se.sars.communication.proto.ipc.command.Command.MoveGimbalCommandOrBuilder getMoveGimbalOrBuilder();

  /**
   * <code>.Command.ChangeZoomLevelCommand changeZoomLevel = 6;</code>
   * @return Whether the changeZoomLevel field is set.
   */
  boolean hasChangeZoomLevel();
  /**
   * <code>.Command.ChangeZoomLevelCommand changeZoomLevel = 6;</code>
   * @return The changeZoomLevel.
   */
  edu.rit.se.sars.communication.proto.ipc.command.Command.ChangeZoomLevelCommand getChangeZoomLevel();
  /**
   * <code>.Command.ChangeZoomLevelCommand changeZoomLevel = 6;</code>
   */
  edu.rit.se.sars.communication.proto.ipc.command.Command.ChangeZoomLevelCommandOrBuilder getChangeZoomLevelOrBuilder();

  /**
   * <code>.Command.GetPositionCommand getPosition = 7;</code>
   * @return Whether the getPosition field is set.
   */
  boolean hasGetPosition();
  /**
   * <code>.Command.GetPositionCommand getPosition = 7;</code>
   * @return The getPosition.
   */
  edu.rit.se.sars.communication.proto.ipc.command.Command.GetPositionCommand getGetPosition();
  /**
   * <code>.Command.GetPositionCommand getPosition = 7;</code>
   */
  edu.rit.se.sars.communication.proto.ipc.command.Command.GetPositionCommandOrBuilder getGetPositionOrBuilder();

  /**
   * <code>.Command.GetOrientationCommand getOrientation = 8;</code>
   * @return Whether the getOrientation field is set.
   */
  boolean hasGetOrientation();
  /**
   * <code>.Command.GetOrientationCommand getOrientation = 8;</code>
   * @return The getOrientation.
   */
  edu.rit.se.sars.communication.proto.ipc.command.Command.GetOrientationCommand getGetOrientation();
  /**
   * <code>.Command.GetOrientationCommand getOrientation = 8;</code>
   */
  edu.rit.se.sars.communication.proto.ipc.command.Command.GetOrientationCommandOrBuilder getGetOrientationOrBuilder();

  /**
   * <code>.Command.GetConnectionStateCommand getConnectionState = 9;</code>
   * @return Whether the getConnectionState field is set.
   */
  boolean hasGetConnectionState();
  /**
   * <code>.Command.GetConnectionStateCommand getConnectionState = 9;</code>
   * @return The getConnectionState.
   */
  edu.rit.se.sars.communication.proto.ipc.command.Command.GetConnectionStateCommand getGetConnectionState();
  /**
   * <code>.Command.GetConnectionStateCommand getConnectionState = 9;</code>
   */
  edu.rit.se.sars.communication.proto.ipc.command.Command.GetConnectionStateCommandOrBuilder getGetConnectionStateOrBuilder();

  public edu.rit.se.sars.communication.proto.ipc.command.Command.CommandCase getCommandCase();
}
