# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/Domain.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='common/Domain.proto',
  package='',
  syntax='proto3',
  serialized_options=b'\n#edu.rit.se.sars.proto.common.domainP\001',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x13\x63ommon/Domain.proto\"L\n\rGeoLocation3D\x12\x10\n\x08latitude\x18\x01 \x01(\x01\x12\x11\n\tlongitude\x18\x02 \x01(\x01\x12\x16\n\x0e\x61ltitudeMeters\x18\x03 \x01(\x01\"4\n\rGeoLocation2D\x12\x10\n\x08latitude\x18\x01 \x01(\x01\x12\x11\n\tlongitude\x18\x02 \x01(\x01\".\n\nGeoPolygon\x12 \n\x08vertices\x18\x01 \x03(\x0b\x32\x0e.GeoLocation2D\"L\n\x0bOrientation\x12\x14\n\x0cpitchDegrees\x18\x01 \x01(\x01\x12\x12\n\nyawDegrees\x18\x02 \x01(\x01\x12\x13\n\x0brollDegrees\x18\x03 \x01(\x01\x42\'\n#edu.rit.se.sars.proto.common.domainP\x01\x62\x06proto3'
)




_GEOLOCATION3D = _descriptor.Descriptor(
  name='GeoLocation3D',
  full_name='GeoLocation3D',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='latitude', full_name='GeoLocation3D.latitude', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='longitude', full_name='GeoLocation3D.longitude', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='altitudeMeters', full_name='GeoLocation3D.altitudeMeters', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=23,
  serialized_end=99,
)


_GEOLOCATION2D = _descriptor.Descriptor(
  name='GeoLocation2D',
  full_name='GeoLocation2D',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='latitude', full_name='GeoLocation2D.latitude', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='longitude', full_name='GeoLocation2D.longitude', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=101,
  serialized_end=153,
)


_GEOPOLYGON = _descriptor.Descriptor(
  name='GeoPolygon',
  full_name='GeoPolygon',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='vertices', full_name='GeoPolygon.vertices', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=155,
  serialized_end=201,
)


_ORIENTATION = _descriptor.Descriptor(
  name='Orientation',
  full_name='Orientation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='pitchDegrees', full_name='Orientation.pitchDegrees', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='yawDegrees', full_name='Orientation.yawDegrees', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='rollDegrees', full_name='Orientation.rollDegrees', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=203,
  serialized_end=279,
)

_GEOPOLYGON.fields_by_name['vertices'].message_type = _GEOLOCATION2D
DESCRIPTOR.message_types_by_name['GeoLocation3D'] = _GEOLOCATION3D
DESCRIPTOR.message_types_by_name['GeoLocation2D'] = _GEOLOCATION2D
DESCRIPTOR.message_types_by_name['GeoPolygon'] = _GEOPOLYGON
DESCRIPTOR.message_types_by_name['Orientation'] = _ORIENTATION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GeoLocation3D = _reflection.GeneratedProtocolMessageType('GeoLocation3D', (_message.Message,), {
  'DESCRIPTOR' : _GEOLOCATION3D,
  '__module__' : 'common.Domain_pb2'
  # @@protoc_insertion_point(class_scope:GeoLocation3D)
  })
_sym_db.RegisterMessage(GeoLocation3D)

GeoLocation2D = _reflection.GeneratedProtocolMessageType('GeoLocation2D', (_message.Message,), {
  'DESCRIPTOR' : _GEOLOCATION2D,
  '__module__' : 'common.Domain_pb2'
  # @@protoc_insertion_point(class_scope:GeoLocation2D)
  })
_sym_db.RegisterMessage(GeoLocation2D)

GeoPolygon = _reflection.GeneratedProtocolMessageType('GeoPolygon', (_message.Message,), {
  'DESCRIPTOR' : _GEOPOLYGON,
  '__module__' : 'common.Domain_pb2'
  # @@protoc_insertion_point(class_scope:GeoPolygon)
  })
_sym_db.RegisterMessage(GeoPolygon)

Orientation = _reflection.GeneratedProtocolMessageType('Orientation', (_message.Message,), {
  'DESCRIPTOR' : _ORIENTATION,
  '__module__' : 'common.Domain_pb2'
  # @@protoc_insertion_point(class_scope:Orientation)
  })
_sym_db.RegisterMessage(Orientation)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
