// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common/Domain.proto

package edu.rit.se.sars.communication.proto.common.domain;

public final class Domain {
  private Domain() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GeoLocation3D_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GeoLocation3D_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GeoLocation2D_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GeoLocation2D_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GeoPolygon_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GeoPolygon_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Orientation_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Orientation_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023common/Domain.proto\"L\n\rGeoLocation3D\022\020" +
      "\n\010latitude\030\001 \001(\001\022\021\n\tlongitude\030\002 \001(\001\022\026\n\016a" +
      "ltitudeMeters\030\003 \001(\001\"4\n\rGeoLocation2D\022\020\n\010" +
      "latitude\030\001 \001(\001\022\021\n\tlongitude\030\002 \001(\001\".\n\nGeo" +
      "Polygon\022 \n\010vertices\030\001 \003(\0132\016.GeoLocation2" +
      "D\"L\n\013Orientation\022\024\n\014pitchDegrees\030\001 \001(\001\022\022" +
      "\n\nyawDegrees\030\002 \001(\001\022\023\n\013rollDegrees\030\003 \001(\001B" +
      "5\n1edu.rit.se.sars.communication.proto.c" +
      "ommon.domainP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_GeoLocation3D_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_GeoLocation3D_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GeoLocation3D_descriptor,
        new java.lang.String[] { "Latitude", "Longitude", "AltitudeMeters", });
    internal_static_GeoLocation2D_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_GeoLocation2D_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GeoLocation2D_descriptor,
        new java.lang.String[] { "Latitude", "Longitude", });
    internal_static_GeoPolygon_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_GeoPolygon_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GeoPolygon_descriptor,
        new java.lang.String[] { "Vertices", });
    internal_static_Orientation_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_Orientation_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Orientation_descriptor,
        new java.lang.String[] { "PitchDegrees", "YawDegrees", "RollDegrees", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
