// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common/Domain.proto

package edu.rit.se.sars.communication.proto.common.domain;

public interface GeoPolygonOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GeoPolygon)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .GeoLocation2D vertices = 1;</code>
   */
  java.util.List<edu.rit.se.sars.communication.proto.common.domain.GeoLocation2D> 
      getVerticesList();
  /**
   * <code>repeated .GeoLocation2D vertices = 1;</code>
   */
  edu.rit.se.sars.communication.proto.common.domain.GeoLocation2D getVertices(int index);
  /**
   * <code>repeated .GeoLocation2D vertices = 1;</code>
   */
  int getVerticesCount();
  /**
   * <code>repeated .GeoLocation2D vertices = 1;</code>
   */
  java.util.List<? extends edu.rit.se.sars.communication.proto.common.domain.GeoLocation2DOrBuilder> 
      getVerticesOrBuilderList();
  /**
   * <code>repeated .GeoLocation2D vertices = 1;</code>
   */
  edu.rit.se.sars.communication.proto.common.domain.GeoLocation2DOrBuilder getVerticesOrBuilder(
      int index);
}
