// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common/Domain.proto

package edu.rit.se.sars.communication.proto.common.domain;

/**
 * Protobuf type {@code Orientation}
 */
public final class Orientation extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:Orientation)
    OrientationOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Orientation.newBuilder() to construct.
  private Orientation(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Orientation() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Orientation();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Orientation(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 9: {

            pitchDegrees_ = input.readDouble();
            break;
          }
          case 17: {

            yawDegrees_ = input.readDouble();
            break;
          }
          case 25: {

            rollDegrees_ = input.readDouble();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return edu.rit.se.sars.communication.proto.common.domain.Domain.internal_static_Orientation_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return edu.rit.se.sars.communication.proto.common.domain.Domain.internal_static_Orientation_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            edu.rit.se.sars.communication.proto.common.domain.Orientation.class, edu.rit.se.sars.communication.proto.common.domain.Orientation.Builder.class);
  }

  public static final int PITCHDEGREES_FIELD_NUMBER = 1;
  private double pitchDegrees_;
  /**
   * <code>double pitchDegrees = 1;</code>
   * @return The pitchDegrees.
   */
  @java.lang.Override
  public double getPitchDegrees() {
    return pitchDegrees_;
  }

  public static final int YAWDEGREES_FIELD_NUMBER = 2;
  private double yawDegrees_;
  /**
   * <code>double yawDegrees = 2;</code>
   * @return The yawDegrees.
   */
  @java.lang.Override
  public double getYawDegrees() {
    return yawDegrees_;
  }

  public static final int ROLLDEGREES_FIELD_NUMBER = 3;
  private double rollDegrees_;
  /**
   * <code>double rollDegrees = 3;</code>
   * @return The rollDegrees.
   */
  @java.lang.Override
  public double getRollDegrees() {
    return rollDegrees_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (pitchDegrees_ != 0D) {
      output.writeDouble(1, pitchDegrees_);
    }
    if (yawDegrees_ != 0D) {
      output.writeDouble(2, yawDegrees_);
    }
    if (rollDegrees_ != 0D) {
      output.writeDouble(3, rollDegrees_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (pitchDegrees_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(1, pitchDegrees_);
    }
    if (yawDegrees_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(2, yawDegrees_);
    }
    if (rollDegrees_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(3, rollDegrees_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof edu.rit.se.sars.communication.proto.common.domain.Orientation)) {
      return super.equals(obj);
    }
    edu.rit.se.sars.communication.proto.common.domain.Orientation other = (edu.rit.se.sars.communication.proto.common.domain.Orientation) obj;

    if (java.lang.Double.doubleToLongBits(getPitchDegrees())
        != java.lang.Double.doubleToLongBits(
            other.getPitchDegrees())) return false;
    if (java.lang.Double.doubleToLongBits(getYawDegrees())
        != java.lang.Double.doubleToLongBits(
            other.getYawDegrees())) return false;
    if (java.lang.Double.doubleToLongBits(getRollDegrees())
        != java.lang.Double.doubleToLongBits(
            other.getRollDegrees())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + PITCHDEGREES_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getPitchDegrees()));
    hash = (37 * hash) + YAWDEGREES_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getYawDegrees()));
    hash = (37 * hash) + ROLLDEGREES_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getRollDegrees()));
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static edu.rit.se.sars.communication.proto.common.domain.Orientation parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static edu.rit.se.sars.communication.proto.common.domain.Orientation parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static edu.rit.se.sars.communication.proto.common.domain.Orientation parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static edu.rit.se.sars.communication.proto.common.domain.Orientation parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static edu.rit.se.sars.communication.proto.common.domain.Orientation parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static edu.rit.se.sars.communication.proto.common.domain.Orientation parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static edu.rit.se.sars.communication.proto.common.domain.Orientation parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static edu.rit.se.sars.communication.proto.common.domain.Orientation parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static edu.rit.se.sars.communication.proto.common.domain.Orientation parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static edu.rit.se.sars.communication.proto.common.domain.Orientation parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static edu.rit.se.sars.communication.proto.common.domain.Orientation parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static edu.rit.se.sars.communication.proto.common.domain.Orientation parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(edu.rit.se.sars.communication.proto.common.domain.Orientation prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code Orientation}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Orientation)
      edu.rit.se.sars.communication.proto.common.domain.OrientationOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return edu.rit.se.sars.communication.proto.common.domain.Domain.internal_static_Orientation_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return edu.rit.se.sars.communication.proto.common.domain.Domain.internal_static_Orientation_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              edu.rit.se.sars.communication.proto.common.domain.Orientation.class, edu.rit.se.sars.communication.proto.common.domain.Orientation.Builder.class);
    }

    // Construct using edu.rit.se.sars.communication.proto.common.domain.Orientation.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      pitchDegrees_ = 0D;

      yawDegrees_ = 0D;

      rollDegrees_ = 0D;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return edu.rit.se.sars.communication.proto.common.domain.Domain.internal_static_Orientation_descriptor;
    }

    @java.lang.Override
    public edu.rit.se.sars.communication.proto.common.domain.Orientation getDefaultInstanceForType() {
      return edu.rit.se.sars.communication.proto.common.domain.Orientation.getDefaultInstance();
    }

    @java.lang.Override
    public edu.rit.se.sars.communication.proto.common.domain.Orientation build() {
      edu.rit.se.sars.communication.proto.common.domain.Orientation result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public edu.rit.se.sars.communication.proto.common.domain.Orientation buildPartial() {
      edu.rit.se.sars.communication.proto.common.domain.Orientation result = new edu.rit.se.sars.communication.proto.common.domain.Orientation(this);
      result.pitchDegrees_ = pitchDegrees_;
      result.yawDegrees_ = yawDegrees_;
      result.rollDegrees_ = rollDegrees_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof edu.rit.se.sars.communication.proto.common.domain.Orientation) {
        return mergeFrom((edu.rit.se.sars.communication.proto.common.domain.Orientation)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(edu.rit.se.sars.communication.proto.common.domain.Orientation other) {
      if (other == edu.rit.se.sars.communication.proto.common.domain.Orientation.getDefaultInstance()) return this;
      if (other.getPitchDegrees() != 0D) {
        setPitchDegrees(other.getPitchDegrees());
      }
      if (other.getYawDegrees() != 0D) {
        setYawDegrees(other.getYawDegrees());
      }
      if (other.getRollDegrees() != 0D) {
        setRollDegrees(other.getRollDegrees());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      edu.rit.se.sars.communication.proto.common.domain.Orientation parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (edu.rit.se.sars.communication.proto.common.domain.Orientation) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private double pitchDegrees_ ;
    /**
     * <code>double pitchDegrees = 1;</code>
     * @return The pitchDegrees.
     */
    @java.lang.Override
    public double getPitchDegrees() {
      return pitchDegrees_;
    }
    /**
     * <code>double pitchDegrees = 1;</code>
     * @param value The pitchDegrees to set.
     * @return This builder for chaining.
     */
    public Builder setPitchDegrees(double value) {
      
      pitchDegrees_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>double pitchDegrees = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearPitchDegrees() {
      
      pitchDegrees_ = 0D;
      onChanged();
      return this;
    }

    private double yawDegrees_ ;
    /**
     * <code>double yawDegrees = 2;</code>
     * @return The yawDegrees.
     */
    @java.lang.Override
    public double getYawDegrees() {
      return yawDegrees_;
    }
    /**
     * <code>double yawDegrees = 2;</code>
     * @param value The yawDegrees to set.
     * @return This builder for chaining.
     */
    public Builder setYawDegrees(double value) {
      
      yawDegrees_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>double yawDegrees = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearYawDegrees() {
      
      yawDegrees_ = 0D;
      onChanged();
      return this;
    }

    private double rollDegrees_ ;
    /**
     * <code>double rollDegrees = 3;</code>
     * @return The rollDegrees.
     */
    @java.lang.Override
    public double getRollDegrees() {
      return rollDegrees_;
    }
    /**
     * <code>double rollDegrees = 3;</code>
     * @param value The rollDegrees to set.
     * @return This builder for chaining.
     */
    public Builder setRollDegrees(double value) {
      
      rollDegrees_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>double rollDegrees = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearRollDegrees() {
      
      rollDegrees_ = 0D;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:Orientation)
  }

  // @@protoc_insertion_point(class_scope:Orientation)
  private static final edu.rit.se.sars.communication.proto.common.domain.Orientation DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new edu.rit.se.sars.communication.proto.common.domain.Orientation();
  }

  public static edu.rit.se.sars.communication.proto.common.domain.Orientation getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Orientation>
      PARSER = new com.google.protobuf.AbstractParser<Orientation>() {
    @java.lang.Override
    public Orientation parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Orientation(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Orientation> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Orientation> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public edu.rit.se.sars.communication.proto.common.domain.Orientation getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

