// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common/Domain.proto

package edu.rit.se.sars.communication.proto.common.domain;

public interface OrientationOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Orientation)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>double pitchDegrees = 1;</code>
   * @return The pitchDegrees.
   */
  double getPitchDegrees();

  /**
   * <code>double yawDegrees = 2;</code>
   * @return The yawDegrees.
   */
  double getYawDegrees();

  /**
   * <code>double rollDegrees = 3;</code>
   * @return The rollDegrees.
   */
  double getRollDegrees();
}
