# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ipc/Event.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from common import Domain_pb2 as common_dot_Domain__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ipc/Event.proto',
  package='',
  syntax='proto3',
  serialized_options=b'\n-edu.rit.se.sars.communication.proto.ipc.eventP\001',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0fipc/Event.proto\x1a\x13\x63ommon/Domain.proto\"\xc1\x04\n\x05\x45vent\x12\x18\n\x0b\x63ommandUUID\x18\x01 \x01(\x0cH\x01\x88\x01\x01\x12\x38\n\x10\x63ommandCompleted\x18\x02 \x01(\x0b\x32\x1c.Event.CommandCompletedEventH\x00\x12\x32\n\rbatteryStatus\x18\x03 \x01(\x0b\x32\x19.Event.BatteryStatusEventH\x00\x12\x34\n\x0epositionStatus\x18\x04 \x01(\x0b\x32\x1a.Event.PositionStatusEventH\x00\x12:\n\x11orientationStatus\x18\x05 \x01(\x0b\x32\x1d.Event.OrientationStatusEventH\x00\x12\x36\n\x0f\x63onnectionState\x18\x06 \x01(\x0b\x32\x1b.Event.ConnectionStateEventH\x00\x1a\x17\n\x15\x43ommandCompletedEvent\x1a\x31\n\x12\x42\x61tteryStatusEvent\x12\x1b\n\x13percentageRemaining\x18\x01 \x01(\x02\x1a\x37\n\x13PositionStatusEvent\x12 \n\x08location\x18\x01 \x01(\x0b\x32\x0e.GeoLocation3D\x1a;\n\x16OrientationStatusEvent\x12!\n\x0borientation\x18\x01 \x01(\x0b\x32\x0c.Orientation\x1a+\n\x14\x43onnectionStateEvent\x12\x13\n\x0bisConnected\x18\x01 \x01(\x08\x42\x07\n\x05\x65ventB\x0e\n\x0c_commandUUIDB1\n-edu.rit.se.sars.communication.proto.ipc.eventP\x01\x62\x06proto3'
  ,
  dependencies=[common_dot_Domain__pb2.DESCRIPTOR,])




_EVENT_COMMANDCOMPLETEDEVENT = _descriptor.Descriptor(
  name='CommandCompletedEvent',
  full_name='Event.CommandCompletedEvent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=356,
  serialized_end=379,
)

_EVENT_BATTERYSTATUSEVENT = _descriptor.Descriptor(
  name='BatteryStatusEvent',
  full_name='Event.BatteryStatusEvent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='percentageRemaining', full_name='Event.BatteryStatusEvent.percentageRemaining', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=381,
  serialized_end=430,
)

_EVENT_POSITIONSTATUSEVENT = _descriptor.Descriptor(
  name='PositionStatusEvent',
  full_name='Event.PositionStatusEvent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='location', full_name='Event.PositionStatusEvent.location', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=432,
  serialized_end=487,
)

_EVENT_ORIENTATIONSTATUSEVENT = _descriptor.Descriptor(
  name='OrientationStatusEvent',
  full_name='Event.OrientationStatusEvent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='orientation', full_name='Event.OrientationStatusEvent.orientation', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=489,
  serialized_end=548,
)

_EVENT_CONNECTIONSTATEEVENT = _descriptor.Descriptor(
  name='ConnectionStateEvent',
  full_name='Event.ConnectionStateEvent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='isConnected', full_name='Event.ConnectionStateEvent.isConnected', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=550,
  serialized_end=593,
)

_EVENT = _descriptor.Descriptor(
  name='Event',
  full_name='Event',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='commandUUID', full_name='Event.commandUUID', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='commandCompleted', full_name='Event.commandCompleted', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='batteryStatus', full_name='Event.batteryStatus', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='positionStatus', full_name='Event.positionStatus', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='orientationStatus', full_name='Event.orientationStatus', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='connectionState', full_name='Event.connectionState', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_EVENT_COMMANDCOMPLETEDEVENT, _EVENT_BATTERYSTATUSEVENT, _EVENT_POSITIONSTATUSEVENT, _EVENT_ORIENTATIONSTATUSEVENT, _EVENT_CONNECTIONSTATEEVENT, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='event', full_name='Event.event',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_commandUUID', full_name='Event._commandUUID',
      index=1, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=41,
  serialized_end=618,
)

_EVENT_COMMANDCOMPLETEDEVENT.containing_type = _EVENT
_EVENT_BATTERYSTATUSEVENT.containing_type = _EVENT
_EVENT_POSITIONSTATUSEVENT.fields_by_name['location'].message_type = common_dot_Domain__pb2._GEOLOCATION3D
_EVENT_POSITIONSTATUSEVENT.containing_type = _EVENT
_EVENT_ORIENTATIONSTATUSEVENT.fields_by_name['orientation'].message_type = common_dot_Domain__pb2._ORIENTATION
_EVENT_ORIENTATIONSTATUSEVENT.containing_type = _EVENT
_EVENT_CONNECTIONSTATEEVENT.containing_type = _EVENT
_EVENT.fields_by_name['commandCompleted'].message_type = _EVENT_COMMANDCOMPLETEDEVENT
_EVENT.fields_by_name['batteryStatus'].message_type = _EVENT_BATTERYSTATUSEVENT
_EVENT.fields_by_name['positionStatus'].message_type = _EVENT_POSITIONSTATUSEVENT
_EVENT.fields_by_name['orientationStatus'].message_type = _EVENT_ORIENTATIONSTATUSEVENT
_EVENT.fields_by_name['connectionState'].message_type = _EVENT_CONNECTIONSTATEEVENT
_EVENT.oneofs_by_name['event'].fields.append(
  _EVENT.fields_by_name['commandCompleted'])
_EVENT.fields_by_name['commandCompleted'].containing_oneof = _EVENT.oneofs_by_name['event']
_EVENT.oneofs_by_name['event'].fields.append(
  _EVENT.fields_by_name['batteryStatus'])
_EVENT.fields_by_name['batteryStatus'].containing_oneof = _EVENT.oneofs_by_name['event']
_EVENT.oneofs_by_name['event'].fields.append(
  _EVENT.fields_by_name['positionStatus'])
_EVENT.fields_by_name['positionStatus'].containing_oneof = _EVENT.oneofs_by_name['event']
_EVENT.oneofs_by_name['event'].fields.append(
  _EVENT.fields_by_name['orientationStatus'])
_EVENT.fields_by_name['orientationStatus'].containing_oneof = _EVENT.oneofs_by_name['event']
_EVENT.oneofs_by_name['event'].fields.append(
  _EVENT.fields_by_name['connectionState'])
_EVENT.fields_by_name['connectionState'].containing_oneof = _EVENT.oneofs_by_name['event']
_EVENT.oneofs_by_name['_commandUUID'].fields.append(
  _EVENT.fields_by_name['commandUUID'])
_EVENT.fields_by_name['commandUUID'].containing_oneof = _EVENT.oneofs_by_name['_commandUUID']
DESCRIPTOR.message_types_by_name['Event'] = _EVENT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Event = _reflection.GeneratedProtocolMessageType('Event', (_message.Message,), {

  'CommandCompletedEvent' : _reflection.GeneratedProtocolMessageType('CommandCompletedEvent', (_message.Message,), {
    'DESCRIPTOR' : _EVENT_COMMANDCOMPLETEDEVENT,
    '__module__' : 'ipc.Event_pb2'
    # @@protoc_insertion_point(class_scope:Event.CommandCompletedEvent)
    })
  ,

  'BatteryStatusEvent' : _reflection.GeneratedProtocolMessageType('BatteryStatusEvent', (_message.Message,), {
    'DESCRIPTOR' : _EVENT_BATTERYSTATUSEVENT,
    '__module__' : 'ipc.Event_pb2'
    # @@protoc_insertion_point(class_scope:Event.BatteryStatusEvent)
    })
  ,

  'PositionStatusEvent' : _reflection.GeneratedProtocolMessageType('PositionStatusEvent', (_message.Message,), {
    'DESCRIPTOR' : _EVENT_POSITIONSTATUSEVENT,
    '__module__' : 'ipc.Event_pb2'
    # @@protoc_insertion_point(class_scope:Event.PositionStatusEvent)
    })
  ,

  'OrientationStatusEvent' : _reflection.GeneratedProtocolMessageType('OrientationStatusEvent', (_message.Message,), {
    'DESCRIPTOR' : _EVENT_ORIENTATIONSTATUSEVENT,
    '__module__' : 'ipc.Event_pb2'
    # @@protoc_insertion_point(class_scope:Event.OrientationStatusEvent)
    })
  ,

  'ConnectionStateEvent' : _reflection.GeneratedProtocolMessageType('ConnectionStateEvent', (_message.Message,), {
    'DESCRIPTOR' : _EVENT_CONNECTIONSTATEEVENT,
    '__module__' : 'ipc.Event_pb2'
    # @@protoc_insertion_point(class_scope:Event.ConnectionStateEvent)
    })
  ,
  'DESCRIPTOR' : _EVENT,
  '__module__' : 'ipc.Event_pb2'
  # @@protoc_insertion_point(class_scope:Event)
  })
_sym_db.RegisterMessage(Event)
_sym_db.RegisterMessage(Event.CommandCompletedEvent)
_sym_db.RegisterMessage(Event.BatteryStatusEvent)
_sym_db.RegisterMessage(Event.PositionStatusEvent)
_sym_db.RegisterMessage(Event.OrientationStatusEvent)
_sym_db.RegisterMessage(Event.ConnectionStateEvent)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
