// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ipc/Event.proto

package edu.rit.se.sars.communication.proto.ipc.event;

public interface EventOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Event)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bytes commandUUID = 1;</code>
   * @return Whether the commandUUID field is set.
   */
  boolean hasCommandUUID();
  /**
   * <code>bytes commandUUID = 1;</code>
   * @return The commandUUID.
   */
  com.google.protobuf.ByteString getCommandUUID();

  /**
   * <code>.Event.CommandCompletedEvent commandCompleted = 2;</code>
   * @return Whether the commandCompleted field is set.
   */
  boolean hasCommandCompleted();
  /**
   * <code>.Event.CommandCompletedEvent commandCompleted = 2;</code>
   * @return The commandCompleted.
   */
  edu.rit.se.sars.communication.proto.ipc.event.Event.CommandCompletedEvent getCommandCompleted();
  /**
   * <code>.Event.CommandCompletedEvent commandCompleted = 2;</code>
   */
  edu.rit.se.sars.communication.proto.ipc.event.Event.CommandCompletedEventOrBuilder getCommandCompletedOrBuilder();

  /**
   * <code>.Event.BatteryStatusEvent batteryStatus = 3;</code>
   * @return Whether the batteryStatus field is set.
   */
  boolean hasBatteryStatus();
  /**
   * <code>.Event.BatteryStatusEvent batteryStatus = 3;</code>
   * @return The batteryStatus.
   */
  edu.rit.se.sars.communication.proto.ipc.event.Event.BatteryStatusEvent getBatteryStatus();
  /**
   * <code>.Event.BatteryStatusEvent batteryStatus = 3;</code>
   */
  edu.rit.se.sars.communication.proto.ipc.event.Event.BatteryStatusEventOrBuilder getBatteryStatusOrBuilder();

  /**
   * <code>.Event.PositionStatusEvent positionStatus = 4;</code>
   * @return Whether the positionStatus field is set.
   */
  boolean hasPositionStatus();
  /**
   * <code>.Event.PositionStatusEvent positionStatus = 4;</code>
   * @return The positionStatus.
   */
  edu.rit.se.sars.communication.proto.ipc.event.Event.PositionStatusEvent getPositionStatus();
  /**
   * <code>.Event.PositionStatusEvent positionStatus = 4;</code>
   */
  edu.rit.se.sars.communication.proto.ipc.event.Event.PositionStatusEventOrBuilder getPositionStatusOrBuilder();

  /**
   * <code>.Event.OrientationStatusEvent orientationStatus = 5;</code>
   * @return Whether the orientationStatus field is set.
   */
  boolean hasOrientationStatus();
  /**
   * <code>.Event.OrientationStatusEvent orientationStatus = 5;</code>
   * @return The orientationStatus.
   */
  edu.rit.se.sars.communication.proto.ipc.event.Event.OrientationStatusEvent getOrientationStatus();
  /**
   * <code>.Event.OrientationStatusEvent orientationStatus = 5;</code>
   */
  edu.rit.se.sars.communication.proto.ipc.event.Event.OrientationStatusEventOrBuilder getOrientationStatusOrBuilder();

  /**
   * <code>.Event.ConnectionStateEvent connectionState = 6;</code>
   * @return Whether the connectionState field is set.
   */
  boolean hasConnectionState();
  /**
   * <code>.Event.ConnectionStateEvent connectionState = 6;</code>
   * @return The connectionState.
   */
  edu.rit.se.sars.communication.proto.ipc.event.Event.ConnectionStateEvent getConnectionState();
  /**
   * <code>.Event.ConnectionStateEvent connectionState = 6;</code>
   */
  edu.rit.se.sars.communication.proto.ipc.event.Event.ConnectionStateEventOrBuilder getConnectionStateOrBuilder();

  public edu.rit.se.sars.communication.proto.ipc.event.Event.EventCase getEventCase();
}
