// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ipc/Event.proto

package edu.rit.se.sars.communication.proto.ipc.event;

public final class EventOuterClass {
  private EventOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Event_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Event_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Event_CommandCompletedEvent_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Event_CommandCompletedEvent_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Event_BatteryStatusEvent_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Event_BatteryStatusEvent_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Event_PositionStatusEvent_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Event_PositionStatusEvent_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Event_OrientationStatusEvent_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Event_OrientationStatusEvent_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Event_ConnectionStateEvent_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Event_ConnectionStateEvent_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017ipc/Event.proto\032\023common/Domain.proto\"\301" +
      "\004\n\005Event\022\030\n\013commandUUID\030\001 \001(\014H\001\210\001\001\0228\n\020co" +
      "mmandCompleted\030\002 \001(\0132\034.Event.CommandComp" +
      "letedEventH\000\0222\n\rbatteryStatus\030\003 \001(\0132\031.Ev" +
      "ent.BatteryStatusEventH\000\0224\n\016positionStat" +
      "us\030\004 \001(\0132\032.Event.PositionStatusEventH\000\022:" +
      "\n\021orientationStatus\030\005 \001(\0132\035.Event.Orient" +
      "ationStatusEventH\000\0226\n\017connectionState\030\006 " +
      "\001(\0132\033.Event.ConnectionStateEventH\000\032\027\n\025Co" +
      "mmandCompletedEvent\0321\n\022BatteryStatusEven" +
      "t\022\033\n\023percentageRemaining\030\001 \001(\002\0327\n\023Positi" +
      "onStatusEvent\022 \n\010location\030\001 \001(\0132\016.GeoLoc" +
      "ation3D\032;\n\026OrientationStatusEvent\022!\n\013ori" +
      "entation\030\001 \001(\0132\014.Orientation\032+\n\024Connecti" +
      "onStateEvent\022\023\n\013isConnected\030\001 \001(\010B\007\n\005eve" +
      "ntB\016\n\014_commandUUIDB1\n-edu.rit.se.sars.co" +
      "mmunication.proto.ipc.eventP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          edu.rit.se.sars.communication.proto.common.domain.Domain.getDescriptor(),
        });
    internal_static_Event_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Event_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Event_descriptor,
        new java.lang.String[] { "CommandUUID", "CommandCompleted", "BatteryStatus", "PositionStatus", "OrientationStatus", "ConnectionState", "Event", "CommandUUID", });
    internal_static_Event_CommandCompletedEvent_descriptor =
      internal_static_Event_descriptor.getNestedTypes().get(0);
    internal_static_Event_CommandCompletedEvent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Event_CommandCompletedEvent_descriptor,
        new java.lang.String[] { });
    internal_static_Event_BatteryStatusEvent_descriptor =
      internal_static_Event_descriptor.getNestedTypes().get(1);
    internal_static_Event_BatteryStatusEvent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Event_BatteryStatusEvent_descriptor,
        new java.lang.String[] { "PercentageRemaining", });
    internal_static_Event_PositionStatusEvent_descriptor =
      internal_static_Event_descriptor.getNestedTypes().get(2);
    internal_static_Event_PositionStatusEvent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Event_PositionStatusEvent_descriptor,
        new java.lang.String[] { "Location", });
    internal_static_Event_OrientationStatusEvent_descriptor =
      internal_static_Event_descriptor.getNestedTypes().get(3);
    internal_static_Event_OrientationStatusEvent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Event_OrientationStatusEvent_descriptor,
        new java.lang.String[] { "Orientation", });
    internal_static_Event_ConnectionStateEvent_descriptor =
      internal_static_Event_descriptor.getNestedTypes().get(4);
    internal_static_Event_ConnectionStateEvent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Event_ConnectionStateEvent_descriptor,
        new java.lang.String[] { "IsConnected", });
    edu.rit.se.sars.communication.proto.common.domain.Domain.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
